pub mod constants;
pub mod game;
pub mod brain;
pub mod policy;
pub mod spatial;
pub mod ai;
pub mod physics;
#[cfg(not(target_arch = "wasm32"))]
pub mod trainer;
#[cfg(not(target_arch = "wasm32"))]
pub mod session;
#[cfg(not(target_arch = "wasm32"))]
pub mod svg;
